const promptStyles = require("./prompt-styles");

// ── ChatGPT via LOGGED-OUT browser (no login, no profile) ─────────────────
// Prompts, meta, and calendars are generated by driving the PUBLIC, logged-out
// chatgpt.com composer. No account, no persistent profile, no ngrok. Each call
// uses a FRESH incognito-style context, which means:
//   • No "profile already in use" lock errors (no shared profile)
//   • No content mixing between clients (fresh context every time)
//   • Anonymous rate limits reset per call (fresh context)
// Image generation is handled separately by lib/chatgpt-images.js (Hostinger).

const { chromium } = require("playwright");

// Serial queue so we never launch too many browsers at once. Each call still
// gets its own fresh context; the queue just paces them one at a time.
let _cgptQueue = Promise.resolve();

async function _runOnePromptLoggedOut(promptText) {
  // Fresh, ISOLATED browser each call. We deliberately do NOT use channel:"chrome"
  // because that can ATTACH to your already-open personal Chrome window (sharing
  // its session/cookies and causing the "reusing open Chrome" problem). Instead
  // we launch BUNDLED CHROMIUM with a UNIQUE temp user-data-dir, so every call is
  // a brand-new browser that never touches your real Chrome.
  const os = require("os");
  const p = require("path");
  const f = require("fs");
  const tmpProfile = f.mkdtempSync(p.join(os.tmpdir(), "cgpt-anon-"));

  // launchPersistentContext with a fresh temp dir = its own isolated browser.
  const context = await chromium.launchPersistentContext(tmpProfile, {
    headless: false,                    // visible; flip to true later if desired
    viewport: null,
    args: ["--no-first-run", "--no-default-browser-check", "--start-maximized"]
    // NOTE: no channel:"chrome" — uses Playwright's bundled Chromium, fully isolated.
  });
  const browser = context.browser();    // may be null for persistent context; that's fine
  const page = context.pages()[0] || await context.newPage();

  try {
    // Navigate to chatgpt.com, RETRYING if we get stuck on about:blank. A fresh
    // temp profile's first tab is about:blank; if goto() silently fails (network
    // hiccup, etc.) the page can be left there with nothing to interact with.
    // Retry a few times before giving up, instead of proceeding on a blank page.
    let navigated = false;
    for (let attempt = 1; attempt <= 3 && !navigated; attempt++) {
      await page.goto("https://chatgpt.com/", { waitUntil: "domcontentloaded", timeout: 45000 }).catch(() => {});
      await page.waitForTimeout(3000);
      const url = page.url();
      if (url && url !== "about:blank" && url.includes("chatgpt.com")) {
        navigated = true;
      } else {
        console.log(`[groq] stuck on "${url}" — retry ${attempt}/3`);
        await page.waitForTimeout(2000);
      }
    }
    if (!navigated) throw new Error("Could not navigate away from about:blank after 3 attempts");

    await page.waitForTimeout(3000);
    try { await page.waitForLoadState("networkidle"); } catch {}
    await page.waitForTimeout(1500);

    // Dismiss the "stay logged out" / cookie prompts if present.
    for (const label of ['button:has-text("Stay logged out")', 'a:has-text("Stay logged out")', 'button:has-text("Reject non-essential")', 'button:has-text("Accept all")']) {
      try { const b = page.locator(label).first(); if (await b.isVisible({ timeout: 1500 }).catch(() => false)) { await b.click().catch(() => {}); await page.waitForTimeout(800); } } catch {}
    }

    // Find the composer (logged-out uses the same ProseMirror editor).
    let input = null;
    for (const sel of ["#prompt-textarea", ".ProseMirror", "textarea", "[contenteditable=\'true\']"]) {
      const el = page.locator(sel).first();
      if (await el.waitFor({ state: "visible", timeout: 8000 }).then(() => true).catch(() => false)) { input = el; break; }
    }
    if (!input) throw new Error("ChatGPT composer not found (logged-out)");

    // Insert the whole prompt at once (clipboard paste → insertText → fill).
    await input.click();
    await page.waitForTimeout(400);
    let inserted = false;
    try {
      await context.grantPermissions(["clipboard-read", "clipboard-write"]).catch(() => {});
      await page.evaluate(async (t) => { await navigator.clipboard.writeText(t); }, promptText);
      await input.click();
      await page.keyboard.press("Control+A"); await page.keyboard.press("Delete");
      await page.keyboard.press("Control+V");
      await page.waitForTimeout(700);
      const v = await input.innerText().catch(() => "") || "";
      if (v && v.length > promptText.length * 0.5) inserted = true;
    } catch {}
    if (!inserted) { try { await input.click(); await page.keyboard.press("Control+A"); await page.keyboard.press("Delete"); await page.keyboard.insertText(promptText); inserted = true; } catch {} }
    if (!inserted) { try { await input.fill(promptText); inserted = true; } catch {} }
    if (!inserted) throw new Error("Could not insert prompt (logged-out)");

    await page.waitForTimeout(400);
    await page.keyboard.press("Enter");
    await page.waitForTimeout(3000);

    // Wait for the response to finish, then read the CLEAN assistant text.
    // Logged-out responses live in [data-assistant-markdown] / [data-message-author-role="assistant"].
    const deadline = Date.now() + 180000;
    let response = null, lastLen = 0, stable = 0;
    while (Date.now() < deadline) {
      await page.waitForTimeout(2000);
      const stillGen = await page.evaluate(() => {
        const stop = document.querySelector('button[data-testid="stop-button"], button[aria-label*="Stop"]');
        const streaming = document.querySelector('.result-streaming, [class*="streaming"]');
        return !!(stop || streaming);
      }).catch(() => false);
      const text = await page.evaluate(() => {
        const md = document.querySelectorAll('[data-assistant-markdown]');
        if (md.length) return (md[md.length - 1].innerText || md[md.length - 1].textContent || "").trim();
        const nodes = document.querySelectorAll('[data-message-author-role="assistant"]');
        if (!nodes.length) return "";
        const last = nodes[nodes.length - 1];
        const body = last.querySelector('.markdown, .prose') || last;
        return (body.innerText || body.textContent || "").trim();
      }).catch(() => "");
      if (stillGen) { stable = 0; lastLen = text.length; continue; }
      if (text && text.length > 20) {
        if (text.length === lastLen) { stable++; if (stable >= 2) { response = text; break; } }
        else { stable = 0; lastLen = text.length; }
      }
    }
    if (!response) throw new Error("ChatGPT (logged-out) did not respond in time");
    return response;
  } finally {
    try { await context.close(); } catch {}
    try { if (browser) await browser.close(); } catch {}
    // Delete the throwaway profile dir so temp doesn't fill up.
    try { f.rmSync(tmpProfile, { recursive: true, force: true }); } catch {}
  }
}

// Public entry — serialized so browsers don't pile up. chatLink is ignored now
// (no per-client chat URLs in the logged-out flow; isolation is automatic).
async function callChatGPT(promptText, chatLink) {
  const run = _cgptQueue.then(() => _runOnePromptLoggedOut(promptText), () => _runOnePromptLoggedOut(promptText));
  _cgptQueue = run.then(() => {}, () => {});
  return run;
}

// Image generation moved to lib/chatgpt-images.js (Hostinger mailboxes). This
// stub keeps the export intact but signals callers to use the reference image.
async function generateImage(promptText, chatLink) {
  throw new Error("generateImage disabled — images come from lib/chatgpt-images.js (Hostinger)");
}

// Shim that mimics the tiny slice of the Groq SDK this file used, so the rest of
// the functions below can stay almost identical. It flattens system+user
// messages into one prompt, calls the ChatGPT server, and—when the caller asked
// for JSON—reminds the model to output raw JSON and strips any code fences.
const groq = {
  chat: {
    completions: {
      async create({ messages = [], response_format, _chatLink } = {}) {
        const wantJson = response_format && response_format.type === "json_object";
        const sys = messages.filter(m => m.role === "system").map(m => m.content).join("\n\n");
        const usr = messages.filter(m => m.role !== "system").map(m => m.content).join("\n\n");
        let prompt = [sys, usr].filter(Boolean).join("\n\n");
        if (wantJson) prompt += "\n\nRespond with RAW JSON only — no markdown, no code fences, no commentary.";
        let text = await callChatGPT(prompt, _chatLink);
        if (wantJson) text = text.replace(/```json|```/gi, "").trim();
        // Return in the same shape the code expects: choices[0].message.content
        return { choices: [{ message: { content: text } }] };
      }
    }
  }
};
const MODEL = "chatgpt";   // kept for compatibility; ignored by the shim

// Base rules for styles that don't bring their own (news, voiceover).
const FLOW_RULES = `
HARD REQUIREMENTS for every prompt you write:
- The video MUST be exactly 10 seconds long.
- It MUST be created for Google Flow "Omni" (text+image to video).
- Vertical 9:16 framing, social-media ready.
- Be cinematic and concrete: describe subject, action, camera movement, lighting and mood.
`.trim();

/**
 * Generate ONE Flow-ready prompt for a single calendar idea, in the client's chosen style.
 * `styleKey` selects a preset from lib/prompt-styles.js. `styleInstruction` (optional)
 * overrides with a fully custom template.
 */
// Normalize a requested part count: accepts a number (1-3) or the legacy
// splitParts boolean (true=2). Clamps to 1..3.
function normParts({ parts, splitParts }) {
  let n = Number.isFinite(parts) ? parts : (splitParts ? 2 : 1);
  n = Math.max(1, Math.min(3, Math.round(n)));
  return n;
}

// Build ONE part block (10 seconds) with correct absolute scene timings for
// part index k (0-based). Each part is 10s: k*10 .. k*10+10.
// voiceover: { enabled, language } — when disabled, the block omits the
// Voiceover line entirely (silent/on-screen-text-only clip).
function partBlock(k, voiceover) {
  const base = k * 10;
  const rng = `${base}-${base + 10} sec`;
  const t = [`${base}-${base + 3} sec`, `${base + 3}-${base + 7} sec`, `${base + 7}-${base + 10} sec`];
  const vo = voiceover && voiceover.enabled === false
    ? ""
    : `\nVoiceover (${(voiceover && voiceover.language) || "Hindi/Hinglish"}): "<natural narration in that language, about 25-30 words, matches the visuals>"`;
  return `PART ${k + 1} (${rng}) — <short punchy title>
Scene 1 (${t[0]}): <one vivid sentence — Indian-origin subject, setting, action, camera, lighting>
Scene 2 (${t[1]}): <one vivid sentence, same subject & style>
Scene 3 (${t[2]}): <one vivid sentence, same subject & style>
On-Screen Text: <short catchy line in English, 3-6 words>
Effects: <4-5 comma-separated cinematic effects, e.g. slow-motion, soft glow, light particles, gentle push-in>
Transition: <one short line describing the transition>${vo}`;
}

// Full house-format block for n parts (each 10s). Used by generatePrompt and enhancePrompt.
function houseFormatBlock(n, voiceover) {
  const blocks = [];
  for (let k = 0; k < n; k++) blocks.push(partBlock(k, voiceover));
  return blocks.join("\n\n");
}

async function generatePrompt({ businessName, businessDetails, topic, hook, styleKey, styleInstruction, promptSample, splitParts, parts, chatLink, voiceoverEnabled = true, voiceoverLanguage = "Hindi/Hinglish" }) {
  // Unified house format for ALL clients. `parts` (1/2/3) = number of 10s parts
  // → 10s / 20s / 30s total. Only the brand info + topic change per video.
  const n = normParts({ parts, splitParts });
  const totalSec = n * 10;
  const voiceover = { enabled: voiceoverEnabled !== false, language: voiceoverLanguage || "Hindi/Hinglish" };

  const sys = `You are a senior short-form video creative director for an Indian social-media brand studio.
You write structured, production-ready prompts for an AI text-to-video tool (Google Flow "Omni"/Veo,
which also generates spoken audio).

MANDATORY RULES for every prompt you write:
- People: use ONLY generic, anonymous INDIAN-ORIGIN people (e.g. "a young Indian woman",
  "an Indian family"). NEVER real, named, or famous individuals; no celebrities, politicians,
  athletes, or influencers.
- No real brands, logos, trademarks, or copyrighted characters.
- No politics, news, violence, weapons, blood, medical/graphic, sexual/suggestive, or hateful content.
- NEWS-STYLE TOPICS (current affairs, films, business, tech announcements): present them in a fully
  ANONYMIZED, generic way that keeps the information but removes every identifiable specific —
  never name real films, shows, celebrities, companies, products, agencies, or places. Instead use
  phrasings like "an upcoming Indian entertainment film", "a major tech company", "a new government
  guideline", and attribute softly with "reportedly". Visuals for such topics must use a generic
  anonymous presenter in a fictional studio with abstract graphics, icons, documents, and symbols —
  no recreations of real people, posters, logos, or copyrighted imagery. The viewer should learn
  WHAT happened without the prompt ever containing WHO/WHICH specifically.
- Keep it positive, aspirational, brand-safe, and culturally Indian.
${voiceover.enabled ? `- Every VOICEOVER must be in natural ${voiceover.language} (Roman script if not English), warm and conversational.` : `- This client does NOT want a spoken voiceover — rely on On-Screen Text and visuals only. Do NOT include any "Voiceover" line.`}
- Visuals must be cinematic and concrete: subject, action, camera movement, lighting, mood; realistic 4K.
- Output ONLY the structured format requested — no preamble, no explanation, no markdown fences.`;

  const brandLine = `Brand: ${businessName || "(unnamed brand)"}${businessDetails ? `\nBrand info: ${businessDetails}` : ""}
Video topic: ${topic || "(brand story)"}${hook ? `\nAngle / hook: ${hook}` : ""}`;

  const markers = Array.from({ length: n }, (_, k) => `"PART ${k + 1}"`).join(", ");
  const continuity = n > 1
    ? `Create a ${totalSec}-second vertical 9:16 video as ${n} CONTINUOUS 10-second parts (each PART continues exactly where the previous ended — same subject, setting, wardrobe, lighting and style). Output EXACTLY this structure and NOTHING else. You MUST include the literal markers ${markers}:`
    : `Create a 10-second vertical 9:16 video. Output EXACTLY this structure and NOTHING else:`;

  const user = `${brandLine}

${continuity}

${houseFormatBlock(n, voiceover)}`;

  const res = await groq.chat.completions.create({ _chatLink: chatLink,
    model: MODEL,
    temperature: 0.85,
    max_tokens: 500 + n * 500,
    messages: [
      { role: "system", content: sys },
      { role: "user", content: user }
    ]
  });

  return sanitizePrompt((res.choices[0]?.message?.content || "").trim().replace(/^["']|["']$/g, ""));
}

/**
 * 1B: The user already WROTE a prompt (e.g. from an uploaded Excel calendar).
 * Keep their concept, subject and wording — do NOT rewrite or invent new ideas.
 * Only lightly polish and REFORMAT it into the house two-part structure (so
 * splitting + per-part images work), with Hindi/Hinglish voiceover and
 * Indian-origin people. Returns the reformatted prompt.
 */
async function enhancePrompt({ userPrompt, businessName, businessDetails, splitParts, parts, chatLink, voiceoverEnabled = true, voiceoverLanguage = "Hindi/Hinglish" }) {
  const n = normParts({ parts, splitParts });
  const totalSec = n * 10;
  const markers = Array.from({ length: n }, (_, k) => `"PART ${k + 1}"`).join(", ");
  const voiceover = { enabled: voiceoverEnabled !== false, language: voiceoverLanguage || "Hindi/Hinglish" };

  const sys = `You are a video-prompt FORMATTER, not a writer. You are given a prompt the user
ALREADY wrote. Rules:
- KEEP the user's concept, subject, story, scenes and wording as much as possible.
- Do NOT invent new ideas, products, or scenes. Do NOT change the meaning.
- You may lightly polish grammar/clarity and split the action across the required scenes/parts.
- Enforce safety only if needed: anonymous Indian-origin people (no real/named/famous individuals),
  no real brands/logos, no politics/violence/sexual/hateful content.
${voiceover.enabled ? `- Voiceover must be in natural ${voiceover.language} (Roman script if not English).` : `- This client does NOT want a spoken voiceover — do NOT include any "Voiceover" line.`}
- Output ONLY the structured format below — no preamble, no explanation, no markdown fences.`;

  const user = `Brand: ${businessName || "(unnamed)"}${businessDetails ? `\nBrand info: ${businessDetails}` : ""}

The user's prompt (KEEP its meaning & wording — only reformat + light polish + split):
"""
${userPrompt}
"""

Reformat the SAME content into EXACTLY this ${totalSec}-second structure${n > 1 ? ` as ${n} continuous 10-second parts` : ""}, and NOTHING else. You MUST include the literal markers ${markers}:

${houseFormatBlock(n, voiceover)}`;

  const res = await groq.chat.completions.create({ _chatLink: chatLink,
    model: MODEL,
    temperature: 0.4,   // low — we're reformatting, not brainstorming
    max_tokens: 500 + n * 500,
    messages: [
      { role: "system", content: sys },
      { role: "user", content: user }
    ]
  });

  return sanitizePrompt((res.choices[0]?.message?.content || "").trim().replace(/^["']|["']$/g, ""));
}

// Safety net: scrub words/phrases that commonly trip Google Flow's filters
// (news/politics framing, violence, sexual, derogatory) before the prompt is
// ever sent to Flow. Replaces with neutral equivalents or removes them.
function sanitizePrompt(text) {
  if (!text) return text;
  let p = text;
  const replacements = [
    // news / politics / real-world framing -> neutral
    [/\bbreaking news\b/gi, "update"],
    [/\bnews (anchor|reporter|broadcast|channel|studio|desk|headline|bulletin)\b/gi, "presenter"],
    [/\bnews\b/gi, "update"],
    [/\b(headline|breaking)\b/gi, "highlight"],
    [/\b(politic(s|al|ian)|election|government|minister|president|prime minister)\b/gi, "topic"],
    [/\b(protest|riot|war|attack|terroris[mt]|bomb|shooting|gun|weapon|knife|blood|gore|kill(ing)?|murder|violence|violent|fight)\b/gi, "scene"],
    // sexual / suggestive -> neutral
    [/\b(sexy|sexual|nude|naked|erotic|seductive|lingerie|bikini|cleavage|provocative)\b/gi, "elegant"],
    // derogatory/toxic -> neutral
    [/\b(hate|racist|slur|abusive|offensive|vulgar)\b/gi, "neutral"],
  ];
  for (const [re, sub] of replacements) p = p.replace(re, sub);
  // collapse any double spaces created by replacements
  return p.replace(/[ \t]{2,}/g, " ").trim();
}
// ChatGPT (web UI) often wraps JSON in prose or ```code fences```. Pull the
// first {...} object out and parse it. Returns null if nothing parseable.
function parseJsonLoose(text) {
  if (!text) return null;
  let s = String(text).replace(/```json/gi, "").replace(/```/g, "").trim();
  // Try direct parse first.
  try { return JSON.parse(s); } catch {}
  // Otherwise grab the outermost {...} block and parse that.
  const start = s.indexOf("{");
  const end = s.lastIndexOf("}");
  if (start !== -1 && end !== -1 && end > start) {
    let block = s.slice(start, end + 1);
    try { return JSON.parse(block); } catch {}
    // common web-UI artifacts: smart quotes, trailing commas
    block = block
      .replace(/[\u201C\u201D]/g, '"').replace(/[\u2018\u2019]/g, "'")
      .replace(/,\s*([}\]])/g, "$1");
    try { return JSON.parse(block); } catch {}
  }
  return null;
}

function splitPromptParts(prompt) {
  if (!prompt) return [prompt];
  // Find every "PART n" marker and slice the text between them, so 1/2/3-part
  // prompts all split correctly. The "PART n" label itself is dropped.
  const re = /PART\s*(\d+)\s*[:\-–—]?/gi;
  const marks = [];
  let m;
  while ((m = re.exec(prompt)) !== null) marks.push({ start: m.index, end: re.lastIndex });
  if (marks.length < 2) return [prompt];   // single part (or no markers)
  const out = [];
  for (let i = 0; i < marks.length; i++) {
    const from = marks[i].end;
    const to = i + 1 < marks.length ? marks[i + 1].start : prompt.length;
    const body = prompt.slice(from, to).trim();
    if (body) out.push(body);
  }
  return out.length ? out : [prompt];
}

/**
 * Extract per-part image URLs that ChatGPT embedded in the script using
 * IMAGE_PART1: <url> / IMAGE_PART2: <url> markers. Returns the URLs and the
 * prompt with those marker lines removed (so they don't get typed into Flow).
 */
function extractPartImages(prompt) {
  const images = [];
  const re = /IMAGE[_ ]?PART\s*(\d)\s*:?\s*(https?:\/\/\S+)/gi;
  let m;
  while ((m = re.exec(prompt)) !== null) {
    const idx = Number(m[1]) - 1;
    if (idx >= 0) images[idx] = m[2].trim();
  }
  // Remove the marker lines from the prompt text.
  const cleaned = prompt.replace(/^.*IMAGE[_ ]?PART\s*\d\s*:?.*$/gim, "").replace(/\n{3,}/g, "\n\n").trim();
  return { images, cleaned };
}

/**
 * Generate a content calendar: an array of { scheduled_date, topic, hook }.
 */
async function generateCalendar({ businessName, businessDetails, days = 30, startDate, videosPerDay = 1, chatLink }) {
  const sys = `You are a social-media content strategist. You produce JSON content calendars
for short vertical videos. Always return STRICT JSON, no commentary, no markdown fences.`;

  const user = `Brand: ${businessName}
Brand brief: ${businessDetails || "(none provided)"}

Create a ${days}-day content calendar of distinct, engaging short-video ideas for this brand.
Return JSON ONLY, shaped exactly like:
{"items":[{"day":1,"topic":"...","hook":"..."}, ...]}
- "topic" = a short concrete idea (max ~8 words).
- "hook" = a one-line scroll-stopping angle.
- ${days} items, days 1..${days}, all unique.`;

  const res = await groq.chat.completions.create({ _chatLink: chatLink,
    model: MODEL,
    temperature: 0.9,
    max_tokens: 1500,
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: sys },
      { role: "user", content: user }
    ]
  });

  let parsed;
  try {
    parsed = JSON.parse(res.choices[0]?.message?.content || "{}");
  } catch {
    parsed = { items: [] };
  }

  const base = startDate ? new Date(startDate) : new Date();
  const timeSlots = ["morning", "afternoon", "evening"];
  const items = [];
  
  for (let topicIndex = 0; topicIndex < (parsed.items || []).length; topicIndex++) {
    const dayOffset = Math.floor(topicIndex / videosPerDay);
    const slotIndex = topicIndex % videosPerDay;
    if (dayOffset >= days) break;
    
    const d = new Date(base);
    d.setDate(base.getDate() + dayOffset);
    const it = (parsed.items || [])[topicIndex] || {};
    
    items.push({
      scheduled_date: d.toISOString().slice(0, 10),
      time_slot: timeSlots[slotIndex] || "morning",
      topic: it.topic || `Idea ${topicIndex + 1}`,
      hook: it.hook || ""
    });
  }
  
  return items;
}

/**
 * Generate YouTube publishing metadata for a finished video.
 */
async function generateYouTubeMeta({ businessName, businessDetails, topic, prompt, defaultTags, chatLink }) {
  const sys = `You write YouTube Shorts metadata. Output ONE raw JSON object and NOTHING else —
no explanation, no markdown, no code fences.`;
  const user = `Brand: ${businessName}
Brand brief: ${businessDetails || ""}
Video topic: ${topic || ""}
Video description (prompt used): ${prompt || ""}
${defaultTags ? `Always-include tags: ${defaultTags}` : ""}

Return ONLY this JSON object (fill every field, no empty strings):
{"title":"catchy title <=90 chars","description":"2-4 line engaging description","hashtags":"#a #b #c (3-6 hashtags)","tags":"comma,separated,tags (8-15 tags)"}`;

  let content = "";
  try {
    const res = await groq.chat.completions.create({ _chatLink: chatLink,
      model: MODEL,
      temperature: 0.8,
      max_tokens: 600,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: sys },
        { role: "user", content: user }
      ]
    });
    content = res.choices[0]?.message?.content || "";
  } catch (e) {
    console.log("[groq] generateYouTubeMeta request failed:", e.message);
  }

  const parsed = parseJsonLoose(content);
  if (parsed && (parsed.title || parsed.description || parsed.tags || parsed.hashtags)) {
    return {
      title: parsed.title || topic || businessName,
      description: parsed.description || "",
      hashtags: parsed.hashtags || "",
      tags: parsed.tags || defaultTags || ""
    };
  }

  // Couldn't parse JSON — say so loudly (don't silently ship empty metadata).
  console.log("[groq] generateYouTubeMeta: could not parse JSON from ChatGPT; raw reply was:\n" + content.slice(0, 300));
  return { title: topic || businessName, description: "", hashtags: "", tags: defaultTags || "" };
}

/**
 * Generate a Flow-ready prompt from a news / RSS item. To stay Veo-safe, the
 * (possibly political/real-world) headline is FIRST distilled to a neutral,
 * evergreen THEME — then that safe theme is fed into the SAME unified house
 * template as the calendar (two-part 0-10 / 10-20, scene numbering, on-screen
 * text, effects, Hindi/Hinglish voiceover, Indian-origin people). Pass
 * splitParts=true (from client.split_parts) to get the 20-second two-part video.
 */
async function generateNewsPrompt({ businessName, businessDetails, title, summary, splitParts, parts, chatLink, voiceoverEnabled, voiceoverLanguage, skipThemeDistillation = false }) {
  // PASS 1 — distill the headline down to ONE safe, generic, apolitical theme.
  // The raw headline is used ONLY here and never reaches the video prompt.
  // skipThemeDistillation=true is used by the topic-days feature, where the
  // "headline" is already a client-chosen evergreen topic (e.g. "productivity
  // tips") rather than a real news headline — no distillation needed, but we
  // still run it through the SAME safety-sanitizing pipeline downstream.
  let theme = title || "everyday life";
  if (!skipThemeDistillation) {
    theme = "everyday life";
    try {
      const t = await groq.chat.completions.create({ _chatLink: chatLink,
        model: MODEL, temperature: 0.3, max_tokens: 30,
        messages: [
          { role: "system", content: `Extract the single broad, universal, brand-safe THEME behind a headline,
in 2-5 words. STRICT: no names of people, companies, agencies, places, parties, or events; no
politics, war, crime, disasters, or controversy. Generalize to a neutral evergreen concept
(e.g. "digital privacy", "advances in technology", "changing seasons", "personal finance",
"healthy living", "space exploration"). Output ONLY the theme phrase, nothing else.` },
          { role: "user", content: `Headline: ${title}\nSummary: ${summary || "(none)"}\n\nTheme:` }
        ]
      });
      const got = (t.choices[0]?.message?.content || "").trim().replace(/^["'.]+|["'.]+$/g, "");
      if (got) theme = sanitizePrompt(got).slice(0, 60);
    } catch {}
  }

  // PASS 2 — reuse the SAME house template as the calendar, with the safe theme
  // (or, for topic-days, the article's own content baked into businessDetails
  // by the caller) as the topic. This gives RSS/topic videos the identical
  // multi-part structure, voiceover, on-screen text and effects — and the
  // SAME Google Flow Omni policy guardrails as every other prompt path.
  return generatePrompt({
    businessName,
    businessDetails,
    topic: theme,
    hook: skipThemeDistillation ? (summary || "") : "",
    splitParts,          // legacy boolean (still honored)
    parts,               // 1/2/3 → 10s/20s/30s
    chatLink,
    voiceoverEnabled,
    voiceoverLanguage
  });
}

/**
 * Generate a short SPOKEN voiceover script (the words to be narrated) sized to
 * the clip length. ~24-30 words ≈ 10 seconds.
 */
async function generateVoiceScript({ businessName, topic, prompt, seconds = 10, chatLink }) {
  const words = Math.round((seconds / 10) * 27);
  const sys = `You write punchy spoken voiceover lines for short vertical videos. Output ONLY the
words to be spoken — no stage directions, no quotes, no emojis, no hashtags, no markdown.`;
  const user = `Brand/channel: ${businessName}
Topic: ${topic || ""}
Scene being shown: ${prompt || ""}

Write a natural, engaging voiceover of about ${words} words (≈${seconds} seconds when read aloud)
that narrates this clip. Plain spoken sentences only.`;

  const res = await groq.chat.completions.create({ _chatLink: chatLink,
    model: MODEL,
    temperature: 0.8,
    max_tokens: 200,
    messages: [
      { role: "system", content: sys },
      { role: "user", content: user }
    ]
  });
  return sanitizePrompt((res.choices[0]?.message?.content || "").trim().replace(/^["']|["']$/g, ""));
}

module.exports = { generatePrompt, enhancePrompt, generateImage, splitPromptParts, extractPartImages, sanitizePrompt, generateNewsPrompt, generateCalendar, generateYouTubeMeta, generateVoiceScript, promptStyles };
